name: kine_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # =======================================================
  # PAQUETES DE FIREBASE Y AUTH (ACTUALIZADOS)
  # =Setting estas versiones modernas solucionar√° los conflictos
  # =======================================================
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2 # Esta ya estaba bien
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  # =======================================================

  # Otros paquetes de la app
  provider: ^6.1.5+1
  go_router: ^17.0.0
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.10.2
  file_picker: ^10.3.3
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
